
INSERT INTO Q_EmployeeInfo(EMPID,EMPFNAME,EMPLNAME,DEPARTMENT,PROJECTID,ADDRESS,DOB,GENDER) 
VALUES (1,'Sanjay','Mehra','HR','HYDERABAD(HYD)','01/12/1976','M');

INSERT INTO Q_EmployeeInfo(EMPID,EMPFNAME,EMPLNAME,DEPARTMENT,PROJECTID,ADDRESS,DOB,GENDER) 
VALUES (2,'Ananya','Mishra','Admin','P2','DELHI(DEL)','02/05/1968','F');

INSERT INTO Q_EmployeeInfo(EMPID,EMPFNAME,EMPLNAME,DEPARTMENT,PROJECTID,ADDRESS,DOB,GENDER) 
VALUES (3,'Rohan','Diwan','Account','P3','MUMBAI(BOM)','01/01/1980','M');

INSERT INTO Q_EmployeeInfo(EMPID,EMPFNAME,EMPLNAME,DEPARTMENT,PROJECTID,ADDRESS,DOB,GENDER) 
VALUES (4,'Sonia','Kulkarni','HR','P1','HYDERABAD(HYD)','02/05/1992','F');

INSERT INTO Q_EmployeeInfo(EMPID,EMPFNAME,EMPLNAME,DEPARTMENT,PROJECTID,ADDRESS,DOB,GENDER) 
VALUES (5,'Ankit','Kapoor','Admin','P2','DELHI(DEL)','03/07/1994','M');


/*
Select * from Q_EmployeeInfo;
*/